import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'john@gmail.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'jane@gmail.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: false,
    }
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Luxurious Plastic Tuna',
      slug: 'luxurious-plastic-tuna',
      category: 'Electronics',
      image: 'https://api.lorem.space/image/watch?w=640&h=480&r=4925',
      price: 100,
      brand: 'Luxurious',
      rating: 4.5,
      numReviews: 20,
      countInStock: 20,
      description: 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    },
    {
      name: 'Generic Frozen Soap',
      slug: 'generic-frozen-soap',
      category: 'Electronics',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=1905',
      price: 120,
      brand: 'Generic',
      rating: 3.3,
      numReviews: 14,
      countInStock: 120,
      description: 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    },
  ],
};

export default data;